version: 2

jobs:
  macos-4.2:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: brew install libressl
      - run: swift package generate-xcodeproj
      - run: xcodebuild -scheme VaporExt-Package -enableCodeCoverage YES test
      - run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

  macos-release-4.2:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: brew install libressl
      - run: swift build -c release

  macos-4.1:
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run: brew install libressl
      - run: swift test

  macos-release-4.1:
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run: brew install libressl
      - run: swift build -c release

  linux-4.1:
    docker:
      - image: swift:4.1.3
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux-release-4.1:
    docker:
      - image: swift:4.1.3
    steps:
      - checkout
      - run: swift build -c release

  linux-4.2:
    docker:
      - image: norionomura/swift:swift-4.2-branch
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux-release-4.2:
    docker:
      - image: norionomura/swift:swift-4.2-branch
    steps:
      - checkout
      - run: swift build -c release

  swiftlint:
    docker:
      - image: norionomura/swiftlint
    steps:
      - checkout
      - run: swiftlint

workflows:
  version: 2
  tests:
    jobs:
      - swiftlint
      # Swift 4.1
      - linux-4.1
      - linux-release-4.1
      - macos-4.1
      - macos-release-4.1

      # Swift 4.2
      - linux-4.2
      - linux-release-4.2
      - macos-4.2
      - macos-release-4.2

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux-4.1
      - linux-4.2
      - macos-4.1
      - macos-4.2
