version: 2

jobs:
  macos:
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run: brew install libressl
      - run: swift package generate-xcodeproj
      - run: xcodebuild -scheme VaporExt-Package -enableCodeCoverage YES test
      - run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

  macos-release:
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run: brew install libressl
      - run: swift build -c release

  linux:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run: swift build
      - run: swift test
  
  linux-release:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run: swift build -c release
  
  swiftlint:
    docker:
      - image: norionomura/swiftlint
    steps:
      - checkout
      - run: swiftlint

workflows:
  version: 2
  tests:
    jobs:
      - swiftlint
      - linux
      - linux-release
      - macos
      - macos-release

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux
      - macos
